[package]
name = "dns-in-a-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "client"

[[bin]]
name = "server"

[dependencies]
bytebuffer = "2"
anyhow = "1"
rand = "0.8"
